POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
      "title": "Taikaa muumimaailmassa",
  "author": "Hän Itse",
  "url": "www.jee.com",
  "likes": 2
}

###
GET http://localhost:3003/api/blogs
