POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Taikaa muumimaailmassa",
  "author": "Hän Itse",
  "url": "www.jee.com",
  "likes": 2
}

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/60698106f05bc60b33dfccd4

###
PUT http://localhost:3003/api/blogs/60698106f05bc60b33dfccd4
Content-Type: application/json

{"likes": 13}

###
DELETE http://localhost:3003/api/blogs/6068a769d1765b24ad89af10

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "blogs": [],
    "username": "diiba",
    "name": "Daaba",
    "password": "passwurd"
}