POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer 

  {
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url":
      "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 5
  }

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/60698106f05bc60b33dfccd4

###
PUT http://localhost:3003/api/blogs/606c1b74dd991c26e69e5966
Content-Type: application/json

{"likes": 13}

###
DELETE http://localhost:3003/api/blogs/60698106f05bc60b33dfccd4

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "blogs": [],
    "username": "dibb",
    "name": "Daaba",
    "password": "Daaba"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "dibb",
    "password": "Daaba"
}